import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { consumeBuddyStream, BuddyClient } from '../../src/components/buddy/client';
import { BUDDY_VERSION, emptyTimings, type BuddyReply, type BuddyEvent } from '../../shared/buddyChat';
const reply=(text:string,requestId=randomUUID(),conversationId=randomUUID()):BuddyReply=>({version:BUDDY_VERSION,requestId,conversationId,sessionId:conversationId,revision:1,mode:'guest',task:'NUTRITION_EDUCATION',text,citations:[],missingFields:[],reasonCodes:[],action:null,handover:false,handoverTag:null,handoverStatus:'not_requested',saved:false,timings:emptyTimings()});
function stream(events:unknown[],split=1){const text=events.map(e=>`data: ${JSON.stringify(e)}\n\n`).join(''),bytes=new TextEncoder().encode(text);return new Response(new ReadableStream<Uint8Array>({start(c){for(let i=0;i<bytes.length;i+=split)c.enqueue(bytes.slice(i,i+split));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});}
test('SSE handles Vietnamese code points divided into single bytes',async()=>{const text='Dinh dưỡng, thể lực và sức khỏe.';const result=await consumeBuddyStream(stream([{type:'delta',text},{type:'done',reply:reply(text)}]),()=>{},new AbortController().signal);assert.equal(result.text,text);});
test('SSE rejects missing final confirmation',async()=>{await assert.rejects(()=>consumeBuddyStream(stream([{type:'delta',text:'Một câu.'}]),()=>{},new AbortController().signal),/chưa được xác nhận/);});
test('SSE rejects final text mismatch',async()=>{await assert.rejects(()=>consumeBuddyStream(stream([{type:'delta',text:'A'},{type:'done',reply:reply('B')}]),()=>{},new AbortController().signal),/không khớp/);});
test('SSE rejects extra frames after done',async()=>{await assert.rejects(()=>consumeBuddyStream(stream([{type:'delta',text:'A'},{type:'done',reply:reply('A')},{type:'delta',text:'B'}]),()=>{},new AbortController().signal),/sau khi kết thúc/);});
test('SSE errors are surfaced, not presented as complete',async()=>{const events:BuddyEvent[]=[];await assert.rejects(()=>consumeBuddyStream(stream([{type:'delta',text:'Phần đầu.'},{type:'error',code:'model_failed',message:'Chưa xong.'}]),e=>events.push(e),new AbortController().signal),/Chưa xong/);assert.deepEqual(events.map(e=>e.type),['delta']);});
test('SSE abort stops a pending reader',async()=>{const controller=new AbortController();let cancelled=false;const response=new Response(new ReadableStream({cancel(){cancelled=true;}}));const pending=consumeBuddyStream(response,()=>{},controller.signal);controller.abort();await assert.rejects(()=>pending);assert(cancelled);});
test('SSE malformed JSON and oversized frames fail safely',async()=>{await assert.rejects(()=>consumeBuddyStream(new Response('data: {broken}\n\n'),()=>{},new AbortController().signal));await assert.rejects(()=>consumeBuddyStream(stream([{type:'delta',text:'x'.repeat(15000)}],20000),()=>{},new AbortController().signal));});
function fakeFetcher(handler:(path:string,init:RequestInit)=>Promise<Response>):typeof fetch{return ((input:RequestInfo|URL,init?:RequestInit)=>handler(String(input),init??{})) as typeof fetch;}
test('client sends token but never client history/memberInfo, and does not use browser storage',async()=>{
 const requests:{path:string;init:RequestInit}[]=[];const cid=randomUUID();
 const fetcher=fakeFetcher(async(path,init)=>{requests.push({path,init});if(path.endsWith('/sessions'))return Response.json({conversationId:cid,revision:0,expiresAt:'2027-01-01',mode:'authenticated_user'});const b=JSON.parse(String(init.body));return stream([{type:'meta',requestId:b.requestId,conversationId:cid},{type:'delta',text:'Xin chào.'},{type:'done',reply:reply('Xin chào.',b.requestId,cid)}],100);});
 const client=new BuddyClient({getToken:async()=>'SYNTHETIC_TOKEN',isCurrent:()=>true,fetcher});await client.send('Protein là gì?','vi',()=>{});
 assert.equal((requests[1].init.headers as Record<string,string>).Authorization,'Bearer SYNTHETIC_TOKEN');assert.deepEqual(Object.keys(JSON.parse(String(requests[1].init.body))).sort(),['conversationId','expectedRevision','lang','message','requestId']);assert.equal(requests.length,2);client.dispose();
});
test('token failure does not become guest or trigger request',async()=>{let calls=0;const c=new BuddyClient({getToken:async()=>{throw Error('expired');},isCurrent:()=>true,fetcher:fakeFetcher(async()=>{calls++;return Response.json({});})});await assert.rejects(()=>c.send('Protein là gì?','vi',()=>{}));assert.equal(calls,0);});
test('client does not retry a 401 or a POST',async()=>{let calls=0;const c=new BuddyClient({getToken:async()=>'bad',isCurrent:()=>true,fetcher:fakeFetcher(async()=>{calls++;return Response.json({code:'invalid_token',error:'expired'},{status:401});})});await assert.rejects(()=>c.send('Protein là gì?','vi',()=>{}));assert.equal(calls,1);});
test('client refuses mismatched stream conversation ID',async()=>{const cid=randomUUID();const c=new BuddyClient({getToken:async()=>null,isCurrent:()=>true,fetcher:fakeFetcher(async path=>path.endsWith('/sessions')?Response.json({conversationId:cid,revision:0,mode:'guest',guestToken:'a'.repeat(43)}):stream([{type:'meta',requestId:randomUUID(),conversationId:randomUUID()}]))});await assert.rejects(()=>c.send('Hi','vi',()=>{}),/không khớp/);});
test('late response after identity change cannot render',async()=>{let current=true,resolveSession!:(r:Response)=>void;let events=0;const c=new BuddyClient({getToken:async()=>null,isCurrent:()=>current,fetcher:fakeFetcher(()=>new Promise(r=>{resolveSession=r;}))});const task=c.send('Protein là gì?','vi',()=>{events++;});await new Promise(r=>setTimeout(r,0));current=false;c.dispose();resolveSession(Response.json({conversationId:randomUUID(),revision:0,mode:'guest'}));await assert.rejects(()=>task);assert.equal(events,0);});
test('retry after uncertain outcome resynchronizes revision, not replays original request',async()=>{const cid=randomUUID();const paths:string[]=[];let chatCount=0;const requests:any[]=[];const c=new BuddyClient({getToken:async()=>null,isCurrent:()=>true,fetcher:fakeFetcher(async(path,init)=>{paths.push(path);if(path.endsWith('/sessions'))return Response.json({conversationId:cid,revision:0,mode:'guest',guestToken:'x'.repeat(43)});if(init.method==='GET')return Response.json({conversationId:cid,revision:1,mode:'guest'});const b=JSON.parse(String(init.body));requests.push(b);chatCount++;if(chatCount===1)throw new TypeError('network');return stream([{type:'delta',text:'B'},{type:'done',reply:{...reply('B',b.requestId,cid),revision:2}}]);})});await assert.rejects(()=>c.send('A','vi',()=>{}));await c.send('B','vi',()=>{});assert.equal(paths.filter(p=>p.endsWith('/chat/stream')).length,2);assert.equal(requests[1].expectedRevision,1);assert.notEqual(requests[0].requestId,requests[1].requestId);c.dispose();});
