import test from 'node:test';
import assert from 'node:assert/strict';
import {parsePathwayBundle,assessPathway,pathwayCsv,publicStructureSummary} from '../../shared/pathwayIntake.ts';
import {fixture,reviewedFixture} from './fixtures.ts';
test('roundtrip preserves source section, raw notation, null and dash',()=>{const b=fixture();assert.deepEqual(parsePathwayBundle(b),b);assert.equal(b.observations[0].fields[1].raw,'-');});
test('empty sources fail',()=>{const b=fixture();b.sources=[];assert.throws(()=>parsePathwayBundle(b));});
test('missing observations fail',()=>{const b=fixture();b.observations=[];assert.throws(()=>parsePathwayBundle(b));});
test('duplicate source identifiers fail',()=>{const b=fixture();b.sources.push({...b.sources[0]});assert.throws(()=>parsePathwayBundle(b));});
test('foreign observation reference fails',()=>{const b=fixture();b.observations[0].sourceId='other';assert.throws(()=>parsePathwayBundle(b));});
test('duplicate observation identifiers fail',()=>{const b=fixture();b.observations.push({...b.observations[0]});assert.throws(()=>parsePathwayBundle(b));});
test('unknown fields including arbitrary member ownership rejected',()=>{for(const k of ['uid','memberId','verified','readyForPlanner','currentPain'])assert.throws(()=>parsePathwayBundle({...fixture(),[k]:true}));});
test('redacted field cannot keep hidden source identifiers',()=>{const b=fixture();b.observations[0].fields[0].reading='redacted';assert.throws(()=>parsePathwayBundle(b));});
test('blank is not zero or an inherited value',()=>{const b=fixture();b.observations[0].fields[2].raw='0';assert.throws(()=>parsePathwayBundle(b));});
test('dash state requires a literal dash',()=>{const b=fixture();b.observations[0].fields[1].raw='ditto';assert.throws(()=>parsePathwayBundle(b));});
test('uncertain field cannot silently receive an inferred unit',()=>{const b=fixture();b.observations[0].fields[0].reading='uncertain';b.observations[0].fields[0].unit='kg';assert.throws(()=>parsePathwayBundle(b));});
test('a missing goal cannot be promoted using a batch title',()=>{const b=fixture();b.sources[0].goal='not_stated';assert.throws(()=>parsePathwayBundle(b));});
test('source associations remain a blocker independently of issue list',()=>{const b=fixture();b.issues=[];assert(assessPathway(b).openBlockers.includes('subject_association_unconfirmed'));});
test('uncertainty remains a blocker even after issue resolution',()=>{const b=reviewedFixture();b.observations[0].fields[0].reading='uncertain';assert.equal(assessPathway(b).readyForSourceReview,false);});
test('resolved issues require explicit evidence',()=>{const b=fixture();b.issues[0].status='resolved';assert.throws(()=>parsePathwayBundle(b));});
test('issue sources cannot silently cross unknown subjects',()=>{const b=fixture();b.issues[0].sourceIds=['other'];assert.throws(()=>parsePathwayBundle(b));});
test('repeated rows are preserved but do not become independent progress',()=>{const b=fixture();b.observations[0].duplicateGroup='same-block';b.observations.push({...b.observations[0],id:'row-b'});const r=assessPathway(parsePathwayBundle(b));assert.equal(r.observations,2);assert.equal(r.repeatedGroups,1);assert(r.warnings.includes('repeated_content_not_independent_progress'));});
test('reviewed source is never a planner-ready program',()=>{const r=assessPathway(parsePathwayBundle(reviewedFixture()));assert.equal(r.readyForSourceReview,true);assert.equal(r.eligibleForPlanner,false);});
test('direct identifier removal is an explicit review requirement',()=>assert.throws(()=>parsePathwayBundle({...fixture(),privacy:{directIdentifiersRemoved:false,containsHealthData:true}})));
test('public summary cannot expose source labels or free text',()=>{const b=fixture();b.observations[0].rowLabel='PRIVATE-CANARY';b.issues[0].detail='PRIVATE-CANARY';b.sources[0].subjectGroup='PRIVATE-CANARY';const s=JSON.stringify(publicStructureSummary(b));assert(!s.includes('PRIVATE-CANARY'));assert(!s.includes('fat_loss'));assert(!s.includes('3x8'));});
test('CSV escapes formulas without modifying the raw JSON',()=>{const b=fixture();b.observations[0].fields[0].raw='=1+1';const csv=pathwayCsv(b);assert(csv.includes("'=1+1"));assert.equal(b.observations[0].fields[0].raw,'=1+1');assert(csv.startsWith('\uFEFF'));});
test('CSV newline/quotes are escaped and not executed',()=>{const b=fixture();b.observations[0].fields[0].raw='first\n"second"';assert(pathwayCsv(b).includes('first\n""second""'));});
test('invalid ID and overlong text rejected',()=>{const b=fixture();b.sources[0].id='../profile';assert.throws(()=>parsePathwayBundle(b));const c=fixture();c.observations[0].fields[0].raw='x'.repeat(1601);assert.throws(()=>parsePathwayBundle(c));});
test('private sources cannot mark themselves as reusable knowledge',()=>assert.throws(()=>parsePathwayBundle({...fixture(),usage:'approved_for_members'})));
