import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import type { AddressInfo } from 'node:net';
import {createPathwayRouter} from '../../server/src/companion/pathways/router';
import {MemoryStore} from '../training/helpers';
import {fixture,reviewedFixture} from './fixtures';
async function withApi(fn:(call:(path:string,method?:string,body?:unknown,token?:string)=>Promise<{status:number;data:any;cache:string|null}>,store:MemoryStore)=>Promise<void>,enabled=true){
 const store=new MemoryStore(),app=express();
 app.use('/api',createPathwayRouter({store,enabled:()=>enabled,adminEmails:()=>['admin-a@example.invalid','admin-b@example.invalid'],verifyToken:async token=>{if(token==='bad')throw new Error('no');return{uid:token,email:`${token}@example.invalid`,email_verified:token!=='unverified'};}}));
 const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));
 const call=async(path:string,method='GET',body?:unknown,token='admin-a')=>{const r=await fetch(`http://127.0.0.1:${(server.address()as AddressInfo).port}/api${path}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:r.status,data:await r.json(),cache:r.headers.get('cache-control')};};
 try{await fn(call,store);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
}
const body=(bundle=fixture(),expectedRevision=0)=>({bundle,expectedRevision,privacyConfirmed:true});
test('private intake requires valid verified admin',()=>withApi(async call=>{assert.equal((await call('/cases','GET',undefined,'bad')).status,401);assert.equal((await call('/cases','GET',undefined,'member')).status,403);assert.equal((await call('/cases','GET',undefined,'unverified')).status,403);}));
test('preview never writes',()=>withApi(async(call,store)=>{const r=await call('/preview','POST',{bundle:fixture()});assert.equal(r.status,200);assert.equal(r.data.databaseWrites,0);assert.equal(store.records.size,0);assert.equal(r.cache,'no-store');}));
test('feature off blocks new intake while keeping private export and deletion possible',()=>withApi(async call=>{assert.equal((await call('/preview','POST',{bundle:fixture()})).status,503);assert.equal((await call('/cases')).status,200);},false));
test('consent is mandatory and cannot be spoofed with imported reviewer fields',()=>withApi(async(call,store)=>{assert.equal((await call('/cases/test','PUT',{...body(),privacyConfirmed:false})).status,400);assert.equal((await call('/cases/test','PUT',{...body(),reviewedBy:'other'})).status,400);assert.equal(store.records.size,0);}));
test('repeated save is idempotent and source writes stay out of member data',()=>withApi(async(call,store)=>{let r=await call('/cases/test','PUT',body());assert.equal(r.status,200);r=await call('/cases/test','PUT',body());assert.equal(r.data.replay,true);assert.equal(store.records.size,1);assert([...store.records.keys()].every(k=>k.startsWith('pathway_intake_owners/admin-a/')));}));
test('conflicting stale save cannot overwrite a private case',()=>withApi(async call=>{await call('/cases/test','PUT',body());const b=fixture();b.observations[0].fields[0].raw='changed';assert.equal((await call('/cases/test','PUT',body(b))).status,409);}));
test('another admin cannot read/edit/delete an unshared case',()=>withApi(async call=>{await call('/cases/test','PUT',body());assert.equal((await call('/cases/test','GET',undefined,'admin-b')).status,404);assert.equal((await call('/cases/test','PUT',body(fixture(),1),'admin-b')).status,409);assert.equal((await call('/cases/test','DELETE',{confirmed:true,expectedRevision:1},'admin-b')).status,404);assert.equal((await call('/cases','GET',undefined,'admin-b')).data.cases.length,0);}));
test('review cannot bypass source blockers',()=>withApi(async call=>{await call('/cases/test','PUT',body());assert.equal((await call('/cases/test/review','POST',{expectedRevision:1,transcriptionConfirmed:true,notAPrescriptionConfirmed:true})).status,409);}));
test('review stamps server actor but never makes a program planner eligible',()=>withApi(async call=>{await call('/cases/test','PUT',body(reviewedFixture()));const r=await call('/cases/test/review','POST',{expectedRevision:1,transcriptionConfirmed:true,notAPrescriptionConfirmed:true});assert.equal(r.status,200);assert.equal(r.data.eligibleForPlanner,false);assert.equal((await call('/cases/test')).data.case.reviewedBy,'admin-a');}));
test('editing keeps original source and resets source-reviewed state',()=>withApi(async call=>{const b=reviewedFixture();await call('/cases/test','PUT',body(b));await call('/cases/test/review','POST',{expectedRevision:1,transcriptionConfirmed:true,notAPrescriptionConfirmed:true});b.observations[0].fields[0].raw='human correction';await call('/cases/test','PUT',body(b,2));const d=(await call('/cases/test')).data.case;assert.equal(d.state,'draft');assert.equal(d.originalBundle.observations[0].fields[0].raw,'3x8');assert.equal(d.bundle.observations[0].fields[0].raw,'human correction');assert.equal(d.reviewedAt,null);}));
test('deletion erases raw and original contents and blocks delayed resurrection',()=>withApi(async(call,store)=>{await call('/cases/test','PUT',body());assert.equal((await call('/cases/test','DELETE',{confirmed:true,expectedRevision:1})).status,200);assert.equal((await call('/cases/test')).status,404);assert.equal((await call('/cases/test','PUT',body())).status,409);assert(!JSON.stringify([...store.records]).includes('Synthetic activity'));}));
test('storage error does not pretend a save succeeded or leak source',()=>withApi(async(call,store)=>{store.failReads=true;const r=await call('/cases/test','PUT',body());assert.equal(r.status,503);assert.equal(r.data.code,'pathway_storage_unavailable');assert(!JSON.stringify(r.data).includes('synthetic storage failure'));}));
test('unrecognized ownership/body fields rejected',()=>withApi(async call=>{assert.equal((await call('/cases/test','PUT',{...body(),uid:'member-b'})).status,400);}));
