import test from 'node:test';
import assert from 'node:assert/strict';
import { profileInput as validateProfile, readinessInput as validateReadiness, completionInput, owns, localDay } from '../../server/src/companion/training/validation';
import { catalogueCandidates, makePlan, scoreMuscles, renderPlanIntro } from '../../server/src/companion/training/planner';
import { normalizeLegacy, summarizeHistory, summarizeProgress, normalizeMuscle } from '../../server/src/companion/training/context';
import { parseTrainingIntent, validateIntent, createIntentParser } from '../../server/src/companion/training/intent';
import { TRAINING_GOALS, EXPERIENCE_LEVELS } from '../../shared/training';
import { NOW, ISO, profileInput, profile, readiness, readinessInput, context, catalogue, noCatalogue, session, clone } from './helpers';
const code = (expected: string) => (e: unknown) => !!e && typeof e === 'object' && 'code' in e && e.code === expected;

test('profile requires explicit consent, adult acknowledgment and screening', () => {
  for (const input of [{ consent: false }, { adultConfirmed: false }, { age: 17 }, { healthReviewNeeded: undefined }]) assert.throws(() => validateProfile(profileInput(input as never)));
});
test('profile validation rejects arbitrary UID, non-finite metrics and invalid timezone', () => {
  for (const input of [{ ...profileInput(), uid: 'other' }, profileInput({ heightCm: NaN }), profileInput({ timezone: 'Not/AZone' }), profileInput({ age: '25' as never })]) assert.throws(() => validateProfile(input));
});
test('optional metrics stay null; zero is not an unknown body weight', () => { assert.equal(validateProfile(profileInput()).weightKg, null); assert.throws(() => validateProfile(profileInput({ weightKg: 0 }))); });
test('readiness never defaults to no pain or a reported energy', () => { for (const k of ['confirmed','energy','currentPain','soreness']) { const r = { ...readinessInput() } as Record<string,unknown>; delete r[k]; assert.throws(() => validateReadiness(r)); } });
test('legacy ownership must be consistent across all present owner fields', () => { assert(owns({ uid: 'a' }, 'a')); assert(!owns({ uid: 'a', userId: 'b' }, 'a')); assert(!owns({ memberCode: 'a' }, 'a')); });
test('intent handles Vietnamese durations without modifying history', () => { assert.equal(parseTrainingIntent('Toi co 35 phut, hom nay muon tap chan').availableMinutes,35); assert.equal(parseTrainingIntent('Hom qua toi da tap nguc').intent,'past_report'); assert.equal(parseTrainingIntent('toi bi dau lung').intent,'safety'); });
test('structured intent rejects UID and unsupported enum; no model configured uses rules', async () => { assert.throws(() => validateIntent({ intent:'plan',uid:'x' })); assert.throws(() => validateIntent({ intent:'write_database' })); assert.equal((await createIntentParser({})('lich su tap')).source,'rules'); });
test('muscle normalization is controlled and handles existing bilingual secondary labels', () => { assert.equal(normalizeMuscle('Tay truoc (Biceps)'),'arms'); assert.equal(normalizeMuscle('unmapped-special-muscle'),null); });
test('pain blocks gym and general planning', () => { for (const c of [catalogue(),noCatalogue()]) assert.equal(makePlan(context(),readiness({ currentPain:true }),c,NOW,'p','h').status,'needs_review'); });
test('health-review flag blocks normal planning', () => { assert.equal(makePlan(context({ profile:profile({ healthReviewNeeded:true }) }),readiness(),catalogue(),NOW,'p','h').status,'needs_review'); });
test('missing profile/readiness and stale readiness return needs_input', () => {
  assert.equal(makePlan(context({profile:null}),readiness(),catalogue(),NOW,'p','h').status,'needs_input');
  for (const r of [null, readiness({confirmed:false}), readiness({expiresAt:ISO}), readiness({profileRevision:2})]) assert.equal(makePlan(context(),r,catalogue(),NOW,'p','h').status,'needs_input');
});
test('very low energy is not overridden by motivation or goals', () => { assert.equal(makePlan(context(),readiness({energy:1}),catalogue(),NOW,'p','h').status,'needs_review'); });
test('requested sore group is not quietly substituted', () => { const r=makePlan(context(),readiness({soreness:['legs']}),catalogue(),NOW,'p','h'); assert.equal(r.status,'needs_review'); });
test('same verified gym data produces a bounded gym-grounded plan', () => { const r=makePlan(context(),readiness(),catalogue(),NOW,'p','h'); assert.equal(r.status,'ready'); if(r.status==='ready') { assert.equal(r.plan.mode,'gym_grounded'); assert(r.plan.estimatedMinutes<=35); assert(r.plan.exercises.length>0); assert(r.plan.catalogueRevision); } });
test('empty catalogue produces conceptual structure, not invented equipment or dosage', () => { const r=makePlan(context(),readiness(),noCatalogue(),NOW,'p','h'); assert.equal(r.status,'ready'); if(r.status==='ready') { assert.equal(r.plan.kind,'structure_only'); assert.equal(r.plan.mode,'personalized_general'); assert.deepEqual(r.plan.exercises,[]); assert.equal(r.plan.catalogueRevision,null); assert(r.plan.caveats.includes('structure_only_not_an_exercise_prescription')); } });
for (const [label, patch] of [ ['unverified',{verified:false}], ['sample',{SAMPLE_DATA_ONLY:true}], ['maintenance',{operationalStatus:'under_maintenance'}], ['retired',{operationalStatus:'retired'}], ['unknown',{operationalStatus:'unknown'}], ['broken',{isFunctional:false}] ] as const) test(`${label} equipment is excluded`, () => { const c=catalogue(); c.equipment=c.equipment.map(e=>({...e,...patch})); assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
for (const [label, patch] of [ ['draft',{reviewStatus:'draft'}], ['review pending',{reviewStatus:'needs_review'}], ['rejected',{reviewStatus:'rejected'}], ['sample',{SAMPLE_DATA_ONLY:true}], ['advanced',{difficulty:'advanced'}] ] as const) test(`${label} exercise is excluded for beginner`, () => { const c=catalogue(); c.exercises=c.exercises.map(e=>({...e,...patch})); assert.equal(catalogueCandidates(c,context({profile:profile({experience:'beginner'})}),readiness()).length,0); });
test('zone must be verified and directions must be grounded', () => { const c=catalogue(); c.zones[0].verified=false; assert.equal(catalogueCandidates(c,context(),readiness()).length,0); c.zones[0].verified=true; delete c.zones[0].directionsFromReception; assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
test('all required machines, not one alternative, must be present and usable', () => { const c=catalogue(); c.exercises=c.exercises.map(e=>({...e,requiredEquipmentIds:['test-station-a','missing']})); assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
test('duplicate catalogue IDs fail closed', () => { const c=catalogue(); c.equipment.push(clone(c.equipment[0])); assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
test('no reviewed prescription means no invented sets/reps', () => { const c=catalogue(); for(const e of c.exercises) delete e.trainingPrescription; assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
test('prescription must cover the actual goal and current exercise revision', () => { const c=catalogue(); for(const e of c.exercises) (e.trainingPrescription as any).goals=['strength']; assert.equal(catalogueCandidates(c,context(),readiness()).length,0); for(const e of c.exercises) { (e.trainingPrescription as any).goals=['hypertrophy']; e.revision=2; } assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
test('secondary soreness and unknown muscle labels fail safe', () => { const c=catalogue(); c.exercises=c.exercises.map(e=>({...e,secondaryMuscles:['arms']})); assert.equal(catalogueCandidates(c,context(),readiness({soreness:['arms']})).length,0); c.exercises=c.exercises.map(e=>({...e,secondaryMuscles:['unmapped-muscle']})); assert.equal(catalogueCandidates(c,context(),readiness()).length,0); });
test('member blocked machines and avoided exercise IDs are excluded', () => { const c=catalogue(), ctx=context({profile:profile({avoidedExerciseIds:['test-exercise-a','test-exercise-b']})}); assert.equal(catalogueCandidates(c,ctx,readiness({blockedEquipmentIds:['test-station-c']})).length,0); });
test('partial catalogue uses only supplied candidates, not a made-up third exercise', () => { const c=catalogue(); c.exercises=c.exercises.slice(0,2); const r=makePlan(context(),readiness(),c,NOW,'p','h'); assert.equal(r.status,'ready'); if(r.status==='ready') assert(r.plan.exercises.every(e=>['test-exercise-a','test-exercise-b'].includes(e.exerciseId))); });
test('duration invariants across goals, experience, minutes and energy', () => {
  for(const goal of TRAINING_GOALS) for(const experience of EXPERIENCE_LEVELS) for(const minutes of [10,15,20,35,60,120]) for(const energy of [2,3,4,5]) {
    const r=makePlan(context({profile:profile({goal,experience})}),readiness({availableMinutes:minutes,energy}),catalogue(),NOW,'p','h'); assert.equal(r.status,'ready');
    if(r.status==='ready') { const seconds=r.plan.warmupSeconds+r.plan.cooldownSeconds+r.plan.exercises.reduce((n,e)=>n+e.estimatedSeconds,0)+r.plan.structure.reduce((n,b)=>n+b.seconds,0); assert(seconds<=minutes*60); assert(r.plan.estimatedMinutes<=minutes); }
  }
});
test('general structures distinguish endurance/mobility from strength-oriented patterns', () => { const endurance=makePlan(context({profile:profile({goal:'endurance'})}),readiness(),noCatalogue(),NOW,'p','h'); if(endurance.status==='ready') assert.equal(endurance.plan.structure[0].pattern,'endurance_planning'); });
test('proposed/future/foreign sessions do not count in confirmed history', () => { const s=session(); const result=summarizeHistory([session({status:'proposed' as never}),session({id:'future',performedAt:new Date(NOW+1000).toISOString()}),session({uid:'b',id:'foreign'}),s],[],'member-a',NOW,'Asia/Ho_Chi_Minh'); assert.equal(result.sessionsLast14Days,1); });
test('partial history uses only completed sets and actual muscle groups', () => { const s=session({status:'partial'}); s.exercises.push({exerciseId:null,name:'skipped legs',muscleGroups:['legs'],sets:[],skipped:true}); const result=summarizeHistory([s],[],'member-a',NOW,'Asia/Ho_Chi_Minh'); assert.equal(result.muscleFrequency14Days.chest,1); assert.equal(result.muscleFrequency14Days.legs,0); });
test('legacy entries are opt-in days, not sessions and cannot cross ownership', () => { const rows=[{id:'a',uid:'member-a',date:'2026-09-21',category:'legs',sets:[{reps:10,completed:true}]},{id:'b',uid:'member-a',date:'2026-09-21',category:'chest',sets:[{reps:8,completed:true}]},{id:'c',uid:'member-a',userId:'other',date:'2026-09-21',category:'back',sets:[{reps:10,completed:true}]}]; const days=normalizeLegacy(rows,'member-a',NOW,'Asia/Ho_Chi_Minh'); assert.equal(days.length,1); assert(!days[0].muscleGroups.includes('back')); const h=summarizeHistory([],days,'member-a',NOW,'Asia/Ho_Chi_Minh'); assert.equal(h.sessionsLast14Days,0); assert.equal(h.legacyTrainingDays14,1); assert.equal(h.confirmedSetCount14Days,0); });
test('canonical and legacy same-day group signals are not double counted', () => { const s=session(); const h=summarizeHistory([s],[{id:'l',date:'2026-09-21',muscleGroups:['chest'],completedSets:2,source:'legacy_member_report'}],'member-a',NOW,'Asia/Ho_Chi_Minh'); assert.equal(h.muscleFrequency14Days.chest,1); });
test('history changes deterministic group ranking; recent does not mean unrecovered', () => { const ctx=context(); ctx.summary=summarizeHistory([session()],[],'member-a',NOW,'Asia/Ho_Chi_Minh'); const scores=scoreMuscles(ctx,readiness({desiredMuscles:[]}),NOW); assert(scores.find(s=>s.muscleGroup==='chest')!.score < scores.find(s=>s.muscleGroup==='legs')!.score); assert(!scores.find(s=>s.muscleGroup==='chest')!.excluded); });
test('explicit pain-free request can override recency ranking but never soreness', () => { const ctx=context(); ctx.summary=summarizeHistory([session()],[],'member-a',NOW,'Asia/Ho_Chi_Minh'); const scores=scoreMuscles(ctx,readiness({desiredMuscles:['chest']}),NOW); assert.equal(scores[0].muscleGroup,'chest'); });
test('truncated history disables underrepresentation bonus', () => { const ctx=context(); ctx.summary.muscleFrequency14Days.chest=10; ctx.summary.truncated=true; assert(scoreMuscles(ctx,readiness(),NOW).every(s=>!s.factors.some(f=>f.code==='less_frequent_in_recorded_history'))); });
test('previous load is displayed verbatim, never increased or inferred from height', () => { const ctx=context(); ctx.summary.latestPerformance['test-exercise-a']={performedAt:ISO,sets:[{reps:10,loadKg:40,rpe:7}]}; const e=catalogueCandidates(catalogue(),ctx,readiness())[0]; assert.equal(e.previousPerformance!.sets[0].loadKg,40); assert(!('prescribedLoadKg' in e)); });
test('local day uses user timezone including UTC boundary and DST', () => { assert.equal(localDay('2026-09-21T18:00:00.000Z','Asia/Ho_Chi_Minh'),'2026-09-22'); assert.equal(localDay('2026-03-08T06:30:00.000Z','America/New_York'),'2026-03-08'); });
test('progress requires enough dated measurements, ignores other accounts', () => { const rows=[{uid:'member-a',date:'2026-09-10',weightKg:70},{uid:'member-a',date:'2026-09-15',weightKg:71},{uid:'member-a',date:'2026-09-22',weightKg:72},{uid:'other',date:'2026-09-20',weightKg:40}]; const p=summarizeProgress(rows,'member-a',NOW,'Asia/Ho_Chi_Minh'); assert.equal(p.changeKg,2); assert.equal(p.points.length,3); assert.equal(summarizeProgress(rows.slice(0,2),'member-a',NOW,'Asia/Ho_Chi_Minh').changeKg,null); });
test('personality does not alter planning or authorization', () => { const a=makePlan(context({profile:profile({style:'gentle'})}),readiness(),catalogue(),NOW,'p','h'),b=makePlan(context({profile:profile({style:'energetic'})}),readiness(),catalogue(),NOW,'p','h'); assert.deepEqual(a,b); assert.notEqual(renderPlanIntro('gentle','gym_grounded'),renderPlanIntro('direct','gym_grounded')); });

test('progress chooses newest same-day report rather than query order', () => {
  const rows=[{uid:'a',id:'new',date:'2026-09-20',weightKg:71,reportedAt:'2026-09-20T12:00:00Z'}, {uid:'a',id:'old',date:'2026-09-20',weightKg:70,reportedAt:'2026-09-20T06:00:00Z'}];
  assert.equal(summarizeProgress(rows,'a',NOW,'Asia/Ho_Chi_Minh').points[0].weightKg,71);
  assert.deepEqual(summarizeProgress(rows,'a',NOW,'Asia/Ho_Chi_Minh'), summarizeProgress([...rows].reverse(),'a',NOW,'Asia/Ho_Chi_Minh'));
});
