const EN: Record<string, string> = {
  title: 'Shine Companion', subtitle: 'Member memory & adaptive training', pilot: 'Controlled pilot',
  overview: 'Today', profile: 'My training profile', history: 'Confirmed history', refresh: 'Refresh',
  loading: 'Loading your private training data...', save: 'Save profile', saved: 'Saved successfully.',
  nickname: 'Preferred name', age: 'Age (adult pilot)', goal: 'Goal', experience: 'Experience', minutes: 'Available minutes',
  timezone: 'Time zone', height: 'Height (cm, optional)', weight: 'Weight (kg, optional)', preferences: 'Preferred groups (optional)',
  avoid: 'Avoid exercise IDs (comma separated, optional)', health: 'Do you need professional review before exercise?',
  yes: 'Yes', no: 'No', select: 'Choose explicitly', adult: 'I confirm that I am at least 18 years old.',
  consent: 'I agree to store my self-reported training profile and confirmed sessions. I can export or remove Step 3 data below. Chat history and body measurements are not sent to the intent model.',
  legacy: 'Include my UID-linked legacy workout entries as self-reported training days.',
  style: 'Coaching style', gentle: 'Gentle', energetic: 'Energetic', direct: 'Direct',
  general_fitness: 'General fitness', hypertrophy: 'Muscle building', strength: 'Strength', fat_loss: 'Fat-loss goal (no calorie prescription)', endurance: 'Endurance', mobility: 'Mobility',
  beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced',
  chest: 'Chest', back: 'Back', legs: 'Legs', shoulders: 'Shoulders', arms: 'Arms', core: 'Core',
  ask: 'Ask about today\'s training', askHint: 'For example: I have 35 minutes and want to train legs.', send: 'Understand request',
  readiness: 'How do you feel right now?', energy: 'Energy (1 very low - 5 high)', pain: 'Do you currently have pain?',
  sore: 'Sore groups (leave unselected only if none)', desired: 'Requested groups (optional)', blocked: 'Equipment IDs you report unavailable (optional)',
  readinessConfirm: 'I confirm these are my current self-reported answers, not an assessment by the AI.',
  gymOnly: 'Require a reviewed gym-specific exercise plan; do not use a general structure.', generate: 'Create my plan',
  gym_grounded: 'Reviewed gym exercise plan', personalized_general: 'Personalized general structure',
  structureNotice: 'Equipment and reviewed exercise dosing are not available for this request. These are discussion blocks, not instructions or a prescribed workout. Ask a qualified trainer to choose suitable exercises.',
  why: 'Why this plan?', warmup: 'Warm-up discussion time', cooldown: 'Cool-down discussion time',
  reference: 'Previous confirmed performance (reference only)', cues: 'Reviewed technique cues', location: 'Verified location',
  start: 'Start session / open actual log', cancel: 'Cancel plan', actual: 'What you actually completed',
  actualNotice: 'Leave unfinished items blank. Do not copy proposed sets into the actual log. General sessions are member reports, not proof that every discussion block was completed.',
  name: 'Actual exercise name', reps: 'Actual reps', load: 'External kg (blank = unknown; 0 = none)', rpe: 'RPE 1-10 (optional)',
  addSet: 'Add actual set', addExercise: 'Add actual exercise', skip: 'Skipped', removeSet: 'Remove set', notes: 'Session notes (optional)',
  actualMinutes: 'Actual session minutes', completedConfirm: 'I confirm that these are sets I actually completed.',
  changedProfile: 'My profile changed; this is a record of actual performance under the earlier plan.',
  complete: 'Confirm and save actual performance', retryCompletion: 'Retry the same completion safely',
  emptyHistory: 'No confirmed Step 3 sessions yet. Missing records do not prove that you did not train.',
  export: 'Export Step 3 data', erase: 'Remove Step 3 data', eraseConfirm: 'Remove this account\'s Step 3 profile, plans and sessions? Legacy member records remain unchanged.',
  eraseSession: 'Remove session', eraseSessionConfirm: 'Remove this session from your training history?',
  privacy: 'Step 3 privacy controls', noAuth: 'Use a real Firebase sign-in matching the selected member. Simulated OTP/local storage does not grant access.',
  open: 'Open my training companion', service: 'Back to service chat', close: 'Close training panel',
  recorded: 'Session saved. Your next plan will use the confirmed record.',
  confirmedSessions: 'Confirmed sessions in 14 days', legacyDays: 'Legacy training days in 14 days (not sessions)',
  profile_required: 'Complete your profile first.', readiness_required: 'Explicitly confirm your current readiness.',
  profile_revision_conflict: 'Your profile changed elsewhere. Refresh before saving.',
  professional_review_required: 'Automatic planning is paused. Discuss current pain or relevant health needs with a qualified professional.',
  requested_group_sore: 'The requested group is marked sore. Change your request or seek qualified guidance.',
  very_low_reported_energy: 'No workout has been prescribed because you reported very low energy.',
  pilot_access_required: 'This account has not been admitted to the pilot. An administrator must add its Firebase UID.',
  training_disabled: 'The server training feature flag is off.',
  connection_uncertain: 'The connection was interrupted. Refresh to verify whether the operation was saved. Retrying a completion uses the same payload.',
  confirm_readiness_to_plan: 'I have prepared the request fields. Please review and confirm your current readiness before planning.',
  past_report_not_saved: 'This statement has not changed your history. Only an explicit actual-performance confirmation creates a record.',
  show_confirmed_history: 'Your confirmed sessions are shown in History.',
  training_actions_help: 'Ask what to train today, provide your available minutes, or view confirmed history. Service questions remain in the service chatbot.',
  stale: 'This plan is stale. Refresh and confirm readiness again.', noPlan: 'No current plan. Create one after confirming your readiness.',
  limited: 'Limited context', partial: 'Partial context', established: 'Established recorded context',
  qualityNotice: 'Context availability is not a medical confidence score or proof of recovery.',
  profileFlag: 'Profile', readinessFlag: 'Current readiness', historyFlag: 'Recorded history', gymFlag: 'Reviewed gym data',
  countSets: 'sets', required: 'Complete the required fields.', replay: 'Already saved; no duplicate was created.',
  snapshot: 'Snapshot revisions', rules: 'Pilot heuristic, not a physiological recovery assessment.',
  no_reviewed_executable_plan: 'There is not enough reviewed gym, exercise and dosing data for the requested plan.',
  incompleteSets: 'Enter a name, target group and valid reps for each completed set. Leave unused rows empty.',
  profileChanged: 'Your profile changed after this plan was created.',
  template: 'Conceptual movement block', openPlans: 'Open plans', usePlan: 'Open', more: 'Details'
};
const VI: Record<string, string> = {
  title: 'Shine Companion', subtitle: '\u0110\u1ed3ng h\u00e0nh theo h\u1ed3 s\u01a1 v\u00e0 l\u1ecbch s\u1eed t\u1eadp', pilot: 'B\u1ea3n th\u1eed nghi\u1ec7m c\u00f3 ki\u1ec3m so\u00e1t',
  overview: 'H\u00f4m nay', profile: 'H\u1ed3 s\u01a1 t\u1eadp luy\u1ec7n', history: 'L\u1ecbch s\u1eed \u0111\u00e3 x\u00e1c nh\u1eadn', refresh: 'T\u1ea3i l\u1ea1i',
  save: 'L\u01b0u h\u1ed3 s\u01a1', nickname: 'T\u00ean b\u1ea1n mu\u1ed1n \u0111\u01b0\u1ee3c g\u1ecdi', age: 'Tu\u1ed5i (pilot t\u1eeb 18 tu\u1ed5i)', goal: 'M\u1ee5c ti\u00eau', experience: 'Kinh nghi\u1ec7m', minutes: 'S\u1ed1 ph\u00fat c\u00f3 th\u1ec3 t\u1eadp',
  timezone: 'M\u00fai gi\u1edd', height: 'Chi\u1ec1u cao (cm, kh\u00f4ng b\u1eaft bu\u1ed9c)', weight: 'C\u00e2n n\u1eb7ng (kg, kh\u00f4ng b\u1eaft bu\u1ed9c)',
  yes: 'C\u00f3', no: 'Kh\u00f4ng', select: 'Ch\u1ecdn c\u00e2u tr\u1ea3 l\u1eddi',
  health: 'B\u1ea1n c\u00f3 t\u00ecnh tr\u1ea1ng s\u1ee9c kh\u1ecfe c\u1ea7n chuy\u00ean gia xem x\u00e9t tr\u01b0\u1edbc khi t\u1eadp?',
  adult: 'T\u00f4i x\u00e1c nh\u1eadn \u0111\u00e3 \u0111\u1ee7 18 tu\u1ed5i.',
  consent: 'T\u00f4i \u0111\u1ed3ng \u00fd l\u01b0u h\u1ed3 s\u01a1 t\u1ef1 khai v\u00e0 c\u00e1c bu\u1ed5i t\u1eadp \u0111\u00e3 x\u00e1c nh\u1eadn. T\u00f4i c\u00f3 th\u1ec3 xu\u1ea5t ho\u1eb7c x\u00f3a d\u1eef li\u1ec7u Step 3. L\u1ecbch s\u1eed t\u1eadp v\u00e0 s\u1ed1 \u0111o kh\u00f4ng \u0111\u01b0\u1ee3c g\u1eedi cho m\u00f4 h\u00ecnh hi\u1ec3u y\u00eau c\u1ea7u.',
  legacy: 'S\u1eed d\u1ee5ng nh\u1eadt k\u00fd c\u0169 \u0111\u00fang UID d\u01b0\u1edbi d\u1ea1ng ng\u00e0y t\u1eadp t\u1ef1 b\u00e1o c\u00e1o.',
  style: 'Phong c\u00e1ch \u0111\u1ed3ng h\u00e0nh', gentle: 'Nh\u1eb9 nh\u00e0ng', energetic: 'N\u0103ng \u0111\u1ed9ng', direct: 'Tr\u1ef1c ti\u1ebfp',
  general_fitness: 'Th\u1ec3 l\u1ef1c chung', hypertrophy: 'Ph\u00e1t tri\u1ec3n c\u01a1', strength: 'S\u1ee9c m\u1ea1nh', fat_loss: 'M\u1ee5c ti\u00eau gi\u1ea3m m\u1ee1 (kh\u00f4ng k\u00ea kcal)', endurance: 'S\u1ee9c b\u1ec1n', mobility: 'Linh ho\u1ea1t',
  beginner: 'M\u1edbi t\u1eadp', intermediate: 'Trung c\u1ea5p', advanced: 'N\u00e2ng cao',
  chest: 'Ng\u1ef1c', back: 'L\u01b0ng', legs: 'Ch\u00e2n', shoulders: 'Vai', arms: 'Tay', core: 'Core / b\u1ee5ng',
  ask: 'H\u1ecfi v\u1ec1 bu\u1ed5i t\u1eadp h\u00f4m nay', askHint: 'V\u00ed d\u1ee5: T\u00f4i c\u00f3 35 ph\u00fat, h\u00f4m nay mu\u1ed1n t\u1eadp ch\u00e2n.', send: 'Hi\u1ec3u y\u00eau c\u1ea7u',
  readiness: 'Hi\u1ec7n t\u1ea1i b\u1ea1n c\u1ea3m th\u1ea5y th\u1ebf n\u00e0o?', energy: 'N\u0103ng l\u01b0\u1ee3ng (1 r\u1ea5t th\u1ea5p - 5 cao)', pain: 'Hi\u1ec7n t\u1ea1i b\u1ea1n c\u00f3 \u0111au kh\u00f4ng?',
  sore: 'Nh\u00f3m c\u01a1 c\u00f2n \u00ea m\u1ecfi (kh\u00f4ng ch\u1ecdn n\u1ebfu kh\u00f4ng c\u00f3)', desired: 'Nh\u00f3m c\u01a1 mu\u1ed1n t\u1eadp', generate: 'T\u1ea1o k\u1ebf ho\u1ea1ch',
  readinessConfirm: 'T\u00f4i x\u00e1c nh\u1eadn \u0111\u00e2y l\u00e0 tr\u1ea1ng th\u00e1i t\u1ef1 khai hi\u1ec7n t\u1ea1i, kh\u00f4ng ph\u1ea3i \u0111\u00e1nh gi\u00e1 s\u1ee9c kh\u1ecfe c\u1ee7a AI.',
  gymOnly: 'Ch\u1ec9 t\u1ea1o b\u00e0i t\u1eadp g\u1eafn v\u1edbi gym \u0111\u00e3 x\u00e1c minh, kh\u00f4ng thay b\u1eb1ng khung chung.',
  gym_grounded: 'B\u00e0i t\u1eadp theo d\u1eef li\u1ec7u gym \u0111\u00e3 duy\u1ec7t', personalized_general: 'Khung t\u1eadp c\u00e1 nh\u00e2n h\u00f3a ch\u01b0a g\u1eafn m\u00e1y',
  structureNotice: 'Ch\u01b0a \u0111\u1ee7 d\u1eef li\u1ec7u m\u00e1y, b\u00e0i t\u1eadp v\u00e0 \u0111\u1ecbnh l\u01b0\u1ee3ng \u0111\u00e3 duy\u1ec7t cho y\u00eau c\u1ea7u n\u00e0y. \u0110\u00e2y l\u00e0 khung \u0111\u1ec3 trao \u0111\u1ed5i v\u1edbi HLV, kh\u00f4ng ph\u1ea3i h\u01b0\u1edbng d\u1eabn hay gi\u00e1o \u00e1n th\u1ef1c h\u00e0nh.',
  why: 'V\u00ec sao ch\u1ecdn khung n\u00e0y?', warmup: 'Th\u1eddi gian d\u1ef1 ki\u1ebfn cho kh\u1edfi \u0111\u1ed9ng', cooldown: 'Th\u1eddi gian d\u1ef1 ki\u1ebfn cho th\u1ea3 l\u1ecfng',
  reference: 'Th\u00e0nh t\u00edch \u0111\u00e3 ghi tr\u01b0\u1edbc \u0111\u00f3 (ch\u1ec9 tham kh\u1ea3o)', cues: 'H\u01b0\u1edbng d\u1eabn \u0111\u00e3 duy\u1ec7t', location: 'V\u1ecb tr\u00ed \u0111\u00e3 x\u00e1c minh',
  start: 'B\u1eaft \u0111\u1ea7u bu\u1ed5i / m\u1edf nh\u1eadt k\u00fd', cancel: 'H\u1ee7y k\u1ebf ho\u1ea1ch', actual: 'Ph\u1ea7n b\u1ea1n th\u1ef1c s\u1ef1 \u0111\u00e3 t\u1eadp',
  actualNotice: '\u0110\u1ec3 tr\u1ed1ng ph\u1ea7n ch\u01b0a t\u1eadp. Kh\u00f4ng sao ch\u00e9p s\u1ed1 hi\u1ec7p \u0111\u01b0\u1ee3c g\u1ee3i \u00fd v\u00e0o k\u1ebft qu\u1ea3. Bu\u1ed5i theo khung chung \u0111\u01b0\u1ee3c ghi l\u00e0 t\u1ef1 b\u00e1o c\u00e1o, kh\u00f4ng ch\u1ee9ng minh \u0111\u00e3 l\u00e0m h\u1ebft c\u00e1c kh\u1ed1i.',
  name: 'T\u00ean b\u00e0i th\u1ef1c t\u1ebf', reps: 'S\u1ed1 l\u1ea7n th\u1ef1c t\u1ebf', load: 'T\u1ea1 ngo\u00e0i (kg; tr\u1ed1ng = ch\u01b0a bi\u1ebft; 0 = kh\u00f4ng t\u1ea1)', rpe: 'RPE 1-10 (kh\u00f4ng b\u1eaft bu\u1ed9c)',
  addSet: 'Th\u00eam hi\u1ec7p \u0111\u00e3 t\u1eadp', addExercise: 'Th\u00eam b\u00e0i \u0111\u00e3 t\u1eadp', skip: 'B\u1ecf qua b\u00e0i', removeSet: 'B\u1ecf d\u00f2ng', notes: 'Ghi ch\u00fa (kh\u00f4ng b\u1eaft bu\u1ed9c)',
  actualMinutes: 'S\u1ed1 ph\u00fat t\u1eadp th\u1ef1c t\u1ebf', completedConfirm: 'T\u00f4i x\u00e1c nh\u1eadn \u0111\u00e2y l\u00e0 nh\u1eefng hi\u1ec7p th\u1ef1c s\u1ef1 \u0111\u00e3 ho\u00e0n th\u00e0nh.',
  complete: 'X\u00e1c nh\u1eadn v\u00e0 l\u01b0u k\u1ebft qu\u1ea3', retryCompletion: 'G\u1eedi l\u1ea1i c\u00f9ng k\u1ebft qu\u1ea3, kh\u00f4ng ghi tr\u00f9ng',
  noAuth: 'C\u1ea7n \u0111\u0103ng nh\u1eadp Firebase th\u1eadt, \u0111\u00fang h\u1ed9i vi\u00ean \u0111ang ch\u1ecdn. OTP m\u00f4 ph\u1ecfng ho\u1eb7c localStorage kh\u00f4ng c\u1ea5p quy\u1ec1n.',
  open: 'M\u1edf tr\u1ee3 l\u00fd t\u1eadp luy\u1ec7n', service: 'V\u1ec1 t\u01b0 v\u1ea5n d\u1ecbch v\u1ee5', close: '\u0110\u00f3ng tr\u1ee3 l\u00fd',
  recorded: '\u0110\u00e3 l\u01b0u bu\u1ed5i t\u1eadp. L\u1ea7n g\u1ee3i \u00fd sau s\u1ebd s\u1eed d\u1ee5ng k\u1ebft qu\u1ea3 \u0111\u00e3 x\u00e1c nh\u1eadn.',
  limited: 'Ng\u1eef c\u1ea3nh h\u1ea1n ch\u1ebf', partial: 'Ng\u1eef c\u1ea3nh m\u1ed9t ph\u1ea7n', established: '\u0110\u00e3 c\u00f3 l\u1ecbch s\u1eed v\u00e0 d\u1eef li\u1ec7u gym',
  qualityNotice: '\u0110\u1ed9 \u0111\u1ea7y \u0111\u1ee7 d\u1eef li\u1ec7u kh\u00f4ng ph\u1ea3i \u0111\u1ed9 tin c\u1eady y khoa hay b\u1eb1ng ch\u1ee9ng h\u1ed3i ph\u1ee5c.',
  confirm_readiness_to_plan: '\u0110\u00e3 \u0111i\u1ec1n g\u1ee3i \u00fd cho y\u00eau c\u1ea7u. H\u00e3y ki\u1ec3m tra v\u00e0 x\u00e1c nh\u1eadn tr\u1ea1ng th\u00e1i hi\u1ec7n t\u1ea1i.',
  past_report_not_saved: 'C\u00e2u n\u00f3i n\u00e0y ch\u01b0a l\u00e0m thay \u0111\u1ed5i l\u1ecbch s\u1eed. Ch\u1ec9 thao t\u00e1c x\u00e1c nh\u1eadn k\u1ebft qu\u1ea3 th\u1ef1c t\u1ebf m\u1edbi t\u1ea1o b\u1ea3n ghi.',
  professional_review_required: 'T\u1ea1m d\u1eebng l\u1eadp gi\u00e1o \u00e1n t\u1ef1 \u0111\u1ed9ng. H\u00e3y trao \u0111\u1ed5i v\u1edbi chuy\u00ean gia v\u1ec1 c\u01a1n \u0111au ho\u1eb7c t\u00ecnh tr\u1ea1ng s\u1ee9c kh\u1ecfe hi\u1ec7n t\u1ea1i.',
  pilot_access_required: 'T\u00e0i kho\u1ea3n ch\u01b0a \u0111\u01b0\u1ee3c c\u1ea5p quy\u1ec1n pilot. Qu\u1ea3n tr\u1ecb c\u1ea7n th\u00eam Firebase UID n\u00e0y v\u00e0o danh s\u00e1ch cho ph\u00e9p.',
  training_disabled: 'C\u1edd b\u1eadt t\u00ednh n\u0103ng t\u1eadp luy\u1ec7n ph\u00eda server \u0111ang t\u1eaft.',
  export: 'Xu\u1ea5t d\u1eef li\u1ec7u Step 3', erase: 'X\u00f3a d\u1eef li\u1ec7u Step 3', privacy: 'Quy\u1ec1n ri\u00eang t\u01b0 Step 3',
  emptyHistory: 'Ch\u01b0a c\u00f3 bu\u1ed5i Step 3 \u0111\u00e3 x\u00e1c nh\u1eadn. Thi\u1ebfu b\u1ea3n ghi kh\u00f4ng c\u00f3 ngh\u0129a b\u1ea1n kh\u00f4ng t\u1eadp.'
};
Object.assign(EN, {
  coach_gentle: 'Let us choose a manageable session together.', coach_energetic: 'Shine on. Train with purpose, not pressure.', coach_direct: 'This result follows your confirmed inputs and the available reviewed data.',
  squat_pattern: 'Squat movement pattern', hinge_pattern: 'Hip-hinge movement pattern', horizontal_push: 'Horizontal pushing pattern', horizontal_pull: 'Horizontal pulling pattern', vertical_pull: 'Vertical pulling pattern', shoulder_pattern: 'Shoulder movement discussion', elbow_pattern: 'Elbow movement discussion', trunk_stability: 'Trunk stability discussion', endurance_planning: 'Endurance activity planning', mobility_planning: 'Mobility activity planning',
  goal_hypertrophy_discussion: 'Discuss an appropriate muscle-building activity with your trainer', goal_strength_discussion: 'Discuss suitable strength practice and technique', goal_general_fitness_discussion: 'Discuss a balanced fitness activity', goal_fat_loss_discussion: 'Discuss a sustainable activity; no weight-loss or calorie guarantee', goal_endurance_discussion: 'Choose a suitable activity and intensity with qualified guidance', goal_mobility_discussion: 'Choose appropriate mobility movements with qualified guidance',
  uses_explicit_group_request: 'Uses the muscle groups you explicitly requested.', uses_recorded_history_ranking: 'Uses the frequency in confirmed records; missing records are not proof of no training.', limited_history_balanced_discussion_structure: 'No recent confirmed history: a balanced discussion structure is shown, not an inferred recovery assessment.', uses_confirmed_time_and_readiness: 'Uses the available time and current state you confirmed.',
  explicit_request: 'Your explicit request', stated_preference: 'Your stated preference', recent_training_signal_not_recovery: 'Recent recorded training (not a recovery diagnosis)', less_frequent_in_recorded_history: 'Less frequent in the available records', self_reported_soreness: 'You reported soreness',
  not_medical_or_recovery_assessment: 'This is not a medical assessment or a measurement of muscle recovery.', time_is_estimated_not_a_guarantee: 'Time is an estimate, including assumed transitions; it is not a guarantee.', historical_load_is_reference_only: 'Past loads are reference only. No automatic increase is prescribed.', volume_reduced_for_low_reported_energy: 'Volume/time was reduced because you reported low energy.', structure_only_not_an_exercise_prescription: 'General mode gives discussion blocks, not prescribed exercises.', no_verified_gym_equipment_claims: 'No The Shine machine, floor or location is assumed.', ask_trainer_to_select_exercises_and_technique: 'Ask a qualified trainer to choose suitable exercises and technique.', history_incomplete: 'The history query reached its bound; absence cannot be inferred.',
  legacy_history_not_enabled: 'Legacy workout days are not included unless you opt in.', legacy_self_reported_days_not_sessions: 'Legacy entries are self-reported days, not confirmed Step 3 sessions.', no_confirmed_history: 'There are no confirmed records in the available window.', history_truncated_no_absence_inference: 'History is bounded and incomplete; missing training is not inferred.', need_three_dated_measurements_over_seven_days: 'A change summary requires at least three dated measurements spanning seven days.', observed_change_only_not_health_assessment: 'Observed weight change only; no health conclusion is drawn.', observed_change_only: 'observed change only',
  context_changed: 'The plan, profile, history or readiness changed. Refresh and create a new plan.', readiness_stale: 'Readiness is out of date. Confirm your current state again.', history_changed: 'Your history changed. Refresh before confirming.', completion_conflict: 'A different completion already exists for this plan. Refresh to inspect it.', session_deleted: 'This session was removed. A late retry cannot recreate it.', service_unavailable: 'The service is unavailable. Refresh to check whether the write succeeded; retry the identical completion if necessary.'
});
Object.assign(VI, {
  coach_gentle: 'M\u00ecnh c\u00f9ng ch\u1ecdn m\u1ed9t bu\u1ed5i v\u1eeba s\u1ee9c nh\u00e9.', coach_energetic: 'Shine on. T\u1eadp c\u00f3 m\u1ee5c ti\u00eau, kh\u00f4ng c\u1ea7n t\u1eadp b\u1eb1ng m\u1ecdi gi\u00e1.', coach_direct: '\u0110\u00e2y l\u00e0 k\u1ebft qu\u1ea3 t\u1eeb th\u00f4ng tin b\u1ea1n x\u00e1c nh\u1eadn v\u00e0 d\u1eef li\u1ec7u \u0111\u00e3 duy\u1ec7t.',
  squat_pattern: 'Nh\u00f3m chuy\u1ec3n \u0111\u1ed9ng squat', hinge_pattern: 'Nh\u00f3m chuy\u1ec3n \u0111\u1ed9ng g\u1eadp h\u00f4ng', horizontal_push: 'Nh\u00f3m \u0111\u1ed9ng t\u00e1c \u0111\u1ea9y ngang', horizontal_pull: 'Nh\u00f3m \u0111\u1ed9ng t\u00e1c k\u00e9o ngang', vertical_pull: 'Nh\u00f3m \u0111\u1ed9ng t\u00e1c k\u00e9o d\u1ecdc', shoulder_pattern: 'Trao \u0111\u1ed5i chuy\u1ec3n \u0111\u1ed9ng vai', elbow_pattern: 'Trao \u0111\u1ed5i chuy\u1ec3n \u0111\u1ed9ng tay', trunk_stability: 'Trao \u0111\u1ed5i \u1ed5n \u0111\u1ecbnh th\u00e2n ng\u01b0\u1eddi', endurance_planning: 'Khung ho\u1ea1t \u0111\u1ed9ng s\u1ee9c b\u1ec1n', mobility_planning: 'Khung ho\u1ea1t \u0111\u1ed9ng linh ho\u1ea1t',
  uses_explicit_group_request: 'D\u1ef1a tr\u00ean nh\u00f3m c\u01a1 b\u1ea1n y\u00eau c\u1ea7u.', uses_recorded_history_ranking: 'D\u1ef1a tr\u00ean t\u1ea7n su\u1ea5t trong l\u1ecbch s\u1eed \u0111\u00e3 ghi; thi\u1ebfu b\u1ea3n ghi kh\u00f4ng c\u00f3 ngh\u0129a l\u00e0 ch\u01b0a t\u1eadp.', uses_confirmed_time_and_readiness: 'D\u1ef1a tr\u00ean th\u1eddi gian v\u00e0 tr\u1ea1ng th\u00e1i b\u1ea1n \u0111\u00e3 x\u00e1c nh\u1eadn.',
  explicit_request: 'Y\u00eau c\u1ea7u c\u1ee7a b\u1ea1n', stated_preference: 'S\u1edf th\u00edch \u0111\u00e3 khai b\u00e1o', recent_training_signal_not_recovery: 'V\u1eeba ghi nh\u1eadn t\u1eadp; kh\u00f4ng ph\u1ea3i \u0111\u00e1nh gi\u00e1 ph\u1ee5c h\u1ed3i', less_frequent_in_recorded_history: 'Xu\u1ea5t hi\u1ec7n \u00edt h\u01a1n trong b\u1ea3n ghi', self_reported_soreness: 'B\u1ea1n b\u00e1o c\u00f2n \u00ea m\u1ecfi'
});
for (const goal of ['general_fitness','hypertrophy','strength','fat_loss','endurance','mobility']) { EN[`goal_${goal}`] = `Goal: ${EN[goal]}`; VI[`goal_${goal}`] = `M\u1ee5c ti\u00eau: ${VI[goal] || EN[goal]}`; }
for (const level of ['beginner','intermediate','advanced']) { EN[`experience_${level}`] = `Experience: ${EN[level]}`; VI[`experience_${level}`] = `Kinh nghi\u1ec7m: ${VI[level] || EN[level]}`; }

export function trainingCopy(lang = 'vi') { return (key: string) => (lang === 'vi' ? VI[key] : undefined) ?? EN[key] ?? key.replaceAll('_', ' '); }
